"""switch to many-to-many for projects

Revision ID: 01532af301a4
Revises: b1e6a1520469
Create Date: 2025-08-29 17:58:27.485470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01532af301a4'
down_revision: Union[str, None] = 'b1e6a1520469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_funder',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('funder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funder_id'], ['funding_agencies.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'funder_id')
    )
    op.create_table('project_researcher',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'researcher_id')
    )
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'researchers_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('researchers_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'projects', 'researchers', ['researchers_id'], ['id'])
    op.drop_table('project_researcher')
    op.drop_table('project_funder')
    # ### end Alembic commands ###
